# Tbo/TboThemeBundle/config/config.yml

twig:
    # Registriert einen neuen Namespace für Twig
    paths:
        # Fügen Sie den relativen Pfad zu Ihrem Template-Ordner hinzu, 
        # der die base.html.twig enthält.
        # WICHTIG: Verwenden Sie hier einen eindeutigeren Namen, z.B. @TboGlobal
        # Wenn der Ordner "global" heißt:
        '%kernel.project_dir%/vendor/tbo/tbo-theme-bundle/contao/templates': Tbo_Global