# Raven/RavenThemeBundle/config/services.yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    # Registrierung der Frontend-Module-Controller
    Raven\RavenThemeBundle\Controller\FrontendModule\LogoController: ~
    Raven\RavenThemeBundle\Controller\FrontendModule\FilteredRootPageDependendModulesController: ~
